version: '3.8'

services:
  kafka-broker:
    image: bitnami/kafka:latest
    container_name: kafka-broker
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9094:9094"
    networks:
      - food-delivery-network
    restart: unless-stopped
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9092
      KAFKA_CLUSTERS_0_READONLY: "false"
      KAFKA_CLUSTERS_0_TOPIC_AUTO_CREATE: "true"
    ports:
      - "8080:8080"
    depends_on:
      - kafka-broker
    networks:
      - food-delivery-network
    restart: unless-stopped
  
  user-service:
    image: premkumar850/food-delivery-user-service:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=kafka-broker:9092
    networks:
      - food-delivery-network
    restart: unless-stopped
    depends_on:
      - kafka-broker

  restaurant-service:
    image: premkumar850/food-delivery-restaurant-service:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=kafka-broker:9092
    networks:
      - food-delivery-network
    restart: unless-stopped
    depends_on:
      - kafka-broker

  order-service:
    image: premkumar850/food-delivery-order-service:latest
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=kafka-broker:9092
    networks:
      - food-delivery-network
    restart: unless-stopped
    depends_on:
      - kafka-broker

  food-service:
    image: premkumar850/food-delivery-food-service:latest
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=kafka-broker:9092
    networks:
      - food-delivery-network
    restart: unless-stopped
    depends_on:
      - kafka-broker

  api-gateway:
    image: premkumar850/food-delivery-api-gateway:latest
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - restaurant-service
      - order-service
      - food-service
    environment:
      - NODE_ENV=production
    networks:
      - food-delivery-network
    restart: unless-stopped

networks:
  food-delivery-network:
    driver: bridge